name: E2E Test

on:
  workflow_dispatch:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  skip_check:
    name: Skip Check
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths: '[
            ".github/workflows/e2e-test.yml",
            "gem/**",
            "test/e2e/**",
            "Gemfile.lock",
            "bun.lockb"
            ]'
          paths_ignore: '[
            "gem/config/**",
            "gem/locales/**",
            "!gem/locales/en.yml",
            "**/*.md"
            ]'
          do_not_skip: '["workflow_dispatch"]'

  e2e_test:
    needs: skip_check
    if: ${{ needs.skip_check.outputs.should_skip != 'true' }}
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'
          bundler-cache: true
      - name: Cache Chrome
        id: cache-chrome
        uses: actions/cache@v4
        with:
          path: /tmp/chrome.tar
          key: ${{ runner.os }}-chrome-zenika-latest
      - name: Start Chrome
        run: |
          if [ "${{ steps.cache-chrome.outputs.cache-hit }}" == "true" ]; then
            docker load -i /tmp/chrome.tar
          else
            docker pull zenika/alpine-chrome:latest
            docker save zenika/alpine-chrome:latest > /tmp/chrome.tar
          fi
          docker run -d --network host zenika/alpine-chrome:latest \
            --headless --no-sandbox \
            --use-gl=swiftshader --disable-software-rasterizer --disable-dev-shm-usage \
            --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
      - name: Run E2E Tests
        run: bundle exec rake test:e2e
